import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";


export default function Home() {
    // get image from api and display it
    const [image, setImage] = useState("");

    useEffect(() => {
        fetch("https://api.github.com/users/ry-Rahul")
            .then((res) => res.json())
            .then((data) => {
                setImage(data.avatar_url);
                // console.log(data.avatar_url);
            });
    }, []);

    return (
        <>
            {/* Dummy_______________________________________ */}
  {/* <Dummy/> */}
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* MainComponenet________________________ */}
            <div className={styles.main}>
               
                <div className={styles.middle}>
                    {/* Heading______________________ */}
                    <div className={styles.heading}>
                        <h1>Hunting Coder</h1>
                    </div>

                    <div className={styles.container}>
                        {/* Author________________________ */}
                        <div className={styles.Author}>
                            <div className={styles.authorImage}>
                                <img src={image} alt="image of author" />
                            </div>
                            <div className={styles.authorName}>
                                <h2>Author: Rahul Yadav</h2>
                            </div>
                        </div>

                        {/* BlogContent___________________ */}
                        <div className={styles.content}>
                            <h3>
                                A blog for hunting coders by a hunting coder
                            </h3>
                            <h4>Popular Blogs</h4>
                            <div className={styles.topics}>
                                <h5>How to learn javaScript in 2024?</h5>
                                <p>
                                    JavaScript is the language used to design
                                    logic for the web
                                </p>
                            </div>
                            <div className={styles.topics}>
                                <h5>What is ReactJs ?</h5>
                                <p>
                                    ReactJs is a JavaScript library for
                                    building user interfaces
                                </p>
                            </div>
                            <div className={styles.topics}>
                                <h5>How React work ?</h5>
                                <p>
                                    ReactJs is a JavaScript library for
                                    building user interfaces
                                </p>
                            </div>
                            <div className={styles.topics}>
                                <h5>How you find your Intrest ?</h5>
                                <p>
                                    Visit my blog to find your intrest .....
                                </p>
                            </div>
                            <div className={styles.topics}>
                                <h5>You know why only 10% Btech Student got placements?</h5>
                                <p>
                                   B.tech is a degree which is not for everyone .....
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}
